# python을 이용한 고유값과 고유벡터 문제풀이
> 선형대수학 

- toc:false
- branch: master
- badges: true
- comments: true
- author: 심재인

> 선형대수학

In [1]:
import numpy as np
import numpy.linalg as lin

### 1.
$A$ = $\left[\begin{array}{rrr} 
0&1\\
1&0\\
\end{array}\right]$ 의 고유값과 고유벡터를 구해라.

In [2]:
exEin = np.array([[0,1],[1,0]])

In [3]:
lin.eig(exEin)

(array([ 1., -1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

### 2.
$A$ = $\left[\begin{array}{rrr} 
4&2\\
3&5\\
\end{array}\right]$ 의 고유값과 고유벡터를 구해라.

In [4]:
exEin = np.array([[4,2],[3,5]])

In [5]:
lin.eig(exEin)

(array([2., 7.]),
 array([[-0.70710678, -0.5547002 ],
        [ 0.70710678, -0.83205029]]))

### 3.
$A$ = $\left[\begin{array}{rrr} 
1&0&0\\
0&1&0\\
0&0&1\\
\end{array}\right]$ 의 고유값과 고유벡터를 구해라.

In [6]:
exEin = np.array([[1,0,0],[0,1,0],[0,0,1]])

In [7]:
lin.eig(exEin)

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

### 4.
$A$ = $\left[\begin{array}{rrr} 
-4&-6\\
3&5\\
\end{array}\right]$ 의 고유값과 고유벡터를 구해라.

In [8]:
exEin = np.array([[-4,-6],[3,5]])

In [9]:
lin.eig(exEin)

(array([-1.,  2.]),
 array([[-0.89442719,  0.70710678],
        [ 0.4472136 , -0.70710678]]))

### 5.
$A$ = $\left[\begin{array}{rrr} 
5&-1\\
-2&1\\
\end{array}\right]$ 의 고유값과 고유벡터를 구해라.

In [10]:
exEin = np.array([[5, -1], [-2, 1]])

In [11]:
lin.eig(exEin)

(array([5.44948974, 0.55051026]),
 array([[ 0.91209559,  0.21927526],
        [-0.40997761,  0.97566304]]))