In [1]:
import tensorflow as tf
import tensorflow.experimental.numpy as tnp

In [2]:
tnp.experimental_enable_numpy_behavior()

In [3]:
_X1 = tnp.ones([50,25])*10 
_X1

2022-05-23 23:36:31.857883: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


<tf.Tensor: shape=(50, 25), dtype=float64, numpy=
array([[10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       ...,
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.]])>

In [4]:
_X2 = tnp.zeros([50,25])*10 
_X2

<tf.Tensor: shape=(50, 25), dtype=float64, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])>

In [5]:
tf.concat([_X1,_X2],axis=1)

<tf.Tensor: shape=(50, 50), dtype=float64, numpy=
array([[10., 10., 10., ...,  0.,  0.,  0.],
       [10., 10., 10., ...,  0.,  0.,  0.],
       [10., 10., 10., ...,  0.,  0.,  0.],
       ...,
       [10., 10., 10., ...,  0.,  0.,  0.],
       [10., 10., 10., ...,  0.,  0.,  0.],
       [10., 10., 10., ...,  0.,  0.,  0.]])>

In [6]:
_noise = tnp.random.randn(50*50).reshape(50,50)
_noise

<tf.Tensor: shape=(50, 50), dtype=float64, numpy=
array([[-0.35893472,  1.34715133, -1.09867888, ...,  0.86637446,
         0.76534142,  0.02492512],
       [-2.0924809 ,  0.40532776, -0.22088057, ..., -0.40185935,
         0.45020357,  1.668251  ],
       [ 1.5649497 ,  0.09772148, -0.44497024, ...,  0.95732265,
         1.36476409,  0.81405914],
       ...,
       [-0.15583511, -0.59527225, -0.46381306, ...,  0.16362863,
         1.08391654,  0.49281776],
       [ 1.07869912,  1.07151975, -0.0196227 , ...,  1.25430225,
         0.43976791,  0.40134943],
       [ 0.15613959,  0.10136015,  2.32804407, ..., -1.03957414,
        -2.6255478 , -0.08386856]])>

In [7]:
XXX = tf.concat([_X1,_X2],axis=1) + _noise

In [8]:
XXX=XXX.reshape(1,50,50,1)

In [9]:
plt.imshow(XXX.reshape(50,50),cmap='gray')

NameError: name 'plt' is not defined

In [10]:
conv = tf.keras.layers.Conv2D(2,(2,2))